# docker swarm init
# docker stack deploy -c docker-compose.yml getstartedlab
version: '3'
services:

  app:
    build: .
    container_name: f_recog
    stdin_open: true
    tty: true
    entrypoint: python

    command: [
        "full.py",
        "--data_path=/data",
        "--model=20180402-114759",
        "--photo_dir=samples",
        "--target_file=022.jpg"
    ]    
   
    volumes:
      - ./data:/data
      - ./samples:/data/samples
      - ./app:/app
