version: '3'
services:

  app:
    build: .
    ports:
      - 5999:5000
    volumes:
      - ./app:/app

    working_dir: '/app'
    entrypoint: python
    command: [
        "app.py"
    ]    
    
